

model_list:
  - model_name: #Model Name  # Use this nickname in your application code
    litellm_params:
      model: #Model Name
      api_base: https://router.huggingface.co/v1
      api_key: '#API'
      rpm: 6
      max_tokens: 500
      temperature: 0.5

general_settings:
  master_key: #####
  database_url: postgresql://#######